name: Deploy Bridge
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - './bridge/**'

      # TODO(codebenderhq): add a build step here

      - name: Upload to Deno Deploy
        if: steps.changes.outputs.src == 'true'
        uses: denoland/deployctl@v1
        with:
          project: "clear-donkey-10"
          entrypoint: "./bridge/server.js" # TODO(codebenderhq): update
          
      
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://bridge.sauveur.xyz/update"
      
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}